import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";

const sdkRoot = process.cwd();
const sourceRoot = path.join(sdkRoot, "src");
const distRoot = path.join(sdkRoot, "dist");

async function build() {
  const files = ["index.js", "index.d.ts"];
  await mkdir(distRoot, { recursive: true });

  for (const fileName of files) {
    const sourcePath = path.join(sourceRoot, fileName);
    const distPath = path.join(distRoot, fileName);
    const contents = await readFile(sourcePath, "utf8");
    const banner = "// Generated by scripts/build.mjs.\n";
    await writeFile(distPath, `${banner}${contents}`, "utf8");
  }

  process.stdout.write(`Built HVT TypeScript SDK in ${distRoot}\n`);
}

build().catch((error) => {
  process.stderr.write(`${error.stack || error}\n`);
  process.exitCode = 1;
});
